languages: node_js
node_js: 16.20.0
cache: npm

script:
  - npm i
  - npx playwright install --with-deps
  - npm run test:e2e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
